sudo: required

services:
   - docker

script:
   - ./build.sh build

before_deploy:
   - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
   - provider: script
     script: ./build.sh deploy
     on:
        all_branches: true
